ACTION_SIZE: 4
Levine_Implementation: true
STORED_ACTION_SIZE: 1
STORED_STATE_SIZE: 8
action_noise: 1.0
antithetic: false
avg_episode_length: 200
batch_size: 256
beta_reward_weighting: 1.0
clamp_adv_to_max: false
continuous_actions: false
desire_cum_rew: false
desire_mu_minus_std: false
desire_scalings: null
desire_states: false
desired_reward: 200
desires_size: 1
discount_factor: 0.99
display: false
env_name: LunarLander-v2
eval_agent: false
eval_episodes: 10
eval_every: 10
exp_name: levine_adv_org_rerun
gamename: lunarlander
give_raw_pixels: false
giving_pretrained: false
grad_clip_val: 100
hidden_sizes:
- 8
- 128
- 128
- 64
logdir: exp_dir
lr: 0.001
max_buffer_size: 100000
max_loss_weighting: 20
max_reward: 320
no_reload: true
num_action_repeats: 1
num_grad_steps: 1000
num_rand_action_rollouts: 10
num_val_batches: 2
num_workers: 1
over_max_time_limit_penalty: -50
random_action_epochs: 1
seed: 28
sparse: false
td_lambda: 0.95
time_limit: 300
training_rollouts_per_worker: 20
trim_shape: null
use_Levine_model: true
use_advantage: true
use_lambda_td: true
use_vae: false
val_func_update_iterval: 5
weight_loss: true
