ACTION_SIZE: 4
STORED_ACTION_SIZE: 1
STORED_STATE_SIZE: 8
action_noise: 1.0
antithetic: false
avg_episode_length: 200
batch_size: 256
beta_reward_weighting: 1.0
clamp_adv_to_max: false
continuous_actions: false
desire_advantage: true
desire_cum_rew: false
desire_discounted_rew_to_go: false
desire_horizon: false
desire_mu_minus_std: false
desire_scalings: false
desired_reward: 200
desires_official_order:
- desire_discounted_rew_to_go
- desire_cum_rew
- desire_horizon
- desire_advantage
desires_order:
- desire_advantage
desires_size: 1
discount_factor: 0.99
display: false
env_name: LunarLander-v2
eval_agent: null
eval_episodes: 10
eval_every: 10
exp_name: default
gamename: lunarlander
give_raw_pixels: false
grad_clip_val: 100
hidden_sizes:
- 8
- 64
- 64
implementation: RCP-A
logdir: exp_dir
lr: 0.001
max_adv_clamp_val: 50
max_buffer_size: 100000
max_loss_weighting: 20
max_reward: 320
no_checkpoint: false
no_expo_weighting: true
num_action_repeats: 1
num_grad_steps: 1000
num_rand_action_rollouts: 50
num_val_batches: 2
num_workers: 1
over_max_time_limit_penalty: null
print_statements: 0
random_action_epochs: 1
reload: null
seed: 27
sparse: false
td_lambda: 0.95
time_limit: null
training_rollouts_per_worker: 20
trim_shape: null
use_RCP_buffer: true
use_RCP_desire_sampling: true
use_RCP_model: true
use_exp_weight_losses: true
use_lambda_td: true
use_tune: false
use_vae: false
val_func_update_iterval: 5
